------------------------------------------------------------
-- SAMPLE DATA FOR MEDICAL INVENTORY SYSTEM (MediStock)
-- this is generated by ChatGPT
------------------------------------------------------------

-----------------------------
-- 1. Medications
-----------------------------
INSERT INTO Medications (med_name, generic_name, form, strength, unit, is_controlled, atc_code)
VALUES
('Tylenol', 'Acetaminophen', 'Tablet', '500mg', 'tablet', FALSE, 'N02BE01'),
('Advil', 'Ibuprofen', 'Tablet', '200mg', 'tablet', FALSE, 'M01AE01'),
('Amoxil', 'Amoxicillin', 'Capsule', '250mg', 'capsule', FALSE, 'J01CA04'),
('Ativan', 'Lorazepam', 'Tablet', '1mg', 'tablet', TRUE, 'N05BA06'),
('Ceftriaxone', 'Ceftriaxone', 'Injection', '1g', 'vial', FALSE, 'J01DD04'),
('Insulin', 'Insulin Regular', 'Injection', '100U/mL', 'vial', FALSE, 'A10AB01');

-----------------------------
-- 2. Storage Locations
-----------------------------
INSERT INTO Locations (location_name, description)
VALUES
('Main Cabinet', 'Primary medication storage'),
('Fridge A', 'Temperature-controlled refrigerated storage'),
('Emergency Cart', 'Crash cart with emergency meds'),
('Antibiotics Shelf', 'Shelf dedicated to antibiotic storage'),
('Narcotics Locker', 'Restricted controlled substance locker');

-----------------------------
-- 3. Suppliers (optional)
-----------------------------
INSERT INTO Suppliers (supplier_name, contact_phone, contact_email, address)
VALUES
('HealthCare Wholesale Inc.', '416-555-1212', 'sales@hcwholesale.ca', 'Toronto, ON'),
('Medico Distribution', '647-555-9876', 'orders@medico.com', 'Mississauga, ON'),
('RexPharma Supplies', '905-555-2222', 'support@rexpharma.ca', 'Markham, ON');

-----------------------------
-- 4. Inventory Batches
-----------------------------
INSERT INTO InventoryBatches (med_id, location_id, supplier_id, lot_number, expiry_date, quantity_initial, received_date)
VALUES
(1, 1, 1, 'TYN-001', '2026-01-31', 500, '2025-01-05'),
(1, 1, 1, 'TYN-002', '2026-06-30', 300, '2025-03-01'),

(2, 1, 1, 'ADV-010', '2025-11-30', 400, '2025-01-10'),

(3, 4, 2, 'AMX-100', '2025-12-31', 200, '2025-01-15'),

(4, 5, 3, 'ATV-020', '2025-06-30', 50, '2025-01-10'),

(5, 2, 2, 'CFT-311', '2025-08-20', 120, '2025-01-12'),

(6, 2, 3, 'INS-554', '2025-05-15', 80, '2025-02-01');

-----------------------------
-- 5. Transactions (Stock Movements)
-----------------------------
INSERT INTO Transactions (batch_id, tx_date, tx_type, quantity, reason)
VALUES
-- Tylenol (batch TYN-001)
(1, '2025-01-05', 'IN', 500, 'Initial purchase'),
(1, '2025-02-01', 'OUT', 50, 'Dispensed to patients'),
(1, '2025-02-12', 'OUT', 40, 'Dispensed to patients'),

-- Tylenol (batch TYN-002)
(2, '2025-03-01', 'IN', 300, 'Reorder from supplier'),
(2, '2025-03-10', 'OUT', 30, 'Dispensed to walk-in clinic'),

-- Advil
(3, '2025-01-10', 'IN', 400, 'Initial purchase'),
(3, '2025-02-03', 'OUT', 60, 'Dispensed'),
(3, '2025-02-15', 'OUT', 45, 'Dispensed'),

-- Amoxicillin
(4, '2025-01-15', 'IN', 200, 'Initial purchase'),
(4, '2025-02-20', 'OUT', 60, 'Prescriptions filled'),

-- Ativan (controlled substance)
(5, '2025-01-10', 'IN', 50, 'Controlled substance inventory'),
(5, '2025-01-20', 'OUT', 5, 'Emergency dose'),
(5, '2025-02-01', 'ADJUST', -1, 'Damaged tablet'),

-- Ceftriaxone
(6, '2025-01-12', 'IN', 120, 'Restock'),
(6, '2025-02-02', 'OUT', 25, 'Used in IV therapy'),
(6, '2025-02-05', 'OUT', 10, 'Administered in ER'),

-- Insulin
(7, '2025-02-01', 'IN', 80, 'Initial fridge stock'),
(7, '2025-02-10', 'OUT', 5, 'Administered to patient'),
(7, '2025-02-12', 'OUT', 3, 'Insulin dose');
